### ISSUE TITLE
新增数据库，一键随机

### ISSUE THREAD

**Issue by magisk317** [Houvven/Guise#1]
跪求一键随机功能啊，如果不能全部随机，可以挨个随机也行啊，不然的话丝毫看不出比应用变量的优势何在

**Comment by Mingyueyixi** [comment]
> 跪求一键随机功能啊，如果不能全部随机，可以挨个随机也行啊，不然的话丝毫看不出比应用变量的优势何在

咦～没有这种功能么？要不自己改算了

**Comment by terrytw** [comment]
有能力改的话提PR就好了呀

**Comment by magisk317** [comment]
> 有能力改的话提PR就好了呀

是啊，我要是有能力就不提issue了
另外，你要有能力就提个pr贴上，而不是在这怼我

**Comment by terrytw** [comment]
> > 有能力改的话提PR就好了呀
> 
> 是啊，我要是有能力就不提issue了 另外，你要有能力就提个pr贴上，而不是在这怼我

我是友好的建议Mingyueyixi，因为他说了一句“要不自己改算了”。
怎么你就要急着跳出来和我吵架？
真是无语
github上的中文issue和英文issue水平真不是一个层次上的
说中文的人就知道喊别人加功能，作者辛辛苦苦做了个项目，提要求的时候连句感谢的话都不会说么

“丝毫看不出比应用变量的优势何在”
你是不是没有任何客观说话的能力？
应用变量有针对位置信息的hook吗？应用变量还有持续开发适配新版本修正bug吗？
要是“丝毫看不出比应用变量的优势何在”，你回去用应用变量吧！

**Comment by Rakau** [comment]
> 跪求一键随机功能啊，如果不能全部随机，可以挨个随机也行啊，不然的话丝毫看不出比应用变量的优势何在

那就用应用变量

**Comment by magisk317** [comment]
> 

首先，你回复他，既没at，也没quote reply，我回复了你，你还说我跳出来，还觉得无语，我还觉得你无语呢，你在我帖子下，又没艾特，那可不就是回复的楼主我？自己不会整还嫌别人误会，无语

另外，是作者在应用变量的主题里宣传他这个软件的，要不然你以为我能知道？说好听点是站在别人的肩膀上，说不好听就是蹭人家热度，你咋不自己开个话题？

最后，我本来就是两个都在用，不然我能提出这个建议？

**Comment by magisk317** [comment]
> > > 有能力改的话提PR就好了呀
> > 
> > 
> > 是啊，我要是有能力就不提issue了 另外，你要有能力就提个pr贴上，而不是在这怼我
> 
> 我是友好的建议Mingyueyixi，因为他说了一句“要不自己改算了”。 怎么你就要急着跳出来和我吵架？ 真是无语 github上的中文issue和英文issue水平真不是一个层次上的 说中文的人就知道喊别人加功能，作者辛辛苦苦做了个项目，提要求的时候连句感谢的话都不会说么
> 
> “丝毫看不出比应用变量的优势何在” 你是不是没有任何客观说话的能力？ 应用变量有针对位置信息的hook吗？应用变量还有持续开发适配新版本修正bug吗？ 要是“丝毫看不出比应用变量的优势何在”，你回去用应用变量吧！


首先，你回复他，既没at，也没quote reply，我回复了你，你还说我跳出来，还觉得无语，我还觉得你无语呢，你在我帖子下，又没艾特，那可不就是回复的楼主我？自己不会整还嫌别人误会，无语

另外，是作者在应用变量的主题里宣传他这个软件的，要不然你以为我能知道？说好听点是站在别人的肩膀上，说不好听就是蹭人家热度，你咋不自己开个话题？

最后，我本来就是两个都在用，不然我能提出这个建议？

**Comment by magisk317** [comment]
> > 跪求一键随机功能啊，如果不能全部随机，可以挨个随机也行啊，不然的话丝毫看不出比应用变量的优势何在
> 
> 那就用应用变量

两个都在用，谢谢提醒

**Comment by magisk317** [comment]
另外回复下所有人，这也不是我一个人的需求，我就是提个issue，提个建议，我要有能力就自己贴pr了，所以不用再说“那就回去用应用变量”、“你行你上”之类的话了，不好用还不让人提建议了是吧？
![Screenshot_2023-02-12-14-32-10-753_com coolapk market-edit](https://user-images.githubusercontent.com/93979778/218296970-afaf9ee3-150c-4b7a-84b7-4b7869863081.jpg)
