### ISSUE TITLE
［Feature］能实现控制app是否使用深色模式的功能嘛？

### ISSUE THREAD

**Issue by ShawnRn** [Houvven/Guise#108]
如题 希望做到使部分app不使用深色模式（在系统开启深色模式的情况下）

**Comment by Houvven** [comment]
可以

**Comment by chenyue404** [comment]
https://github.com/KieronQuinn/DarQ

**Comment by Houvven** [comment]
已实现 https://github.com/Houvven/Guise/blob/050e1f3e3d933e022854173a56b3e23c849e81a5/hook/src/main/kotlin/com/houvven/guise/hook/hooker/ResourceConfigurationHooker.kt#L33
