### ISSUE TITLE
source code of newer version and license?

### ISSUE THREAD

**Issue by rhjdvsgsgks** [Houvven/Guise#121]
hi. is there any plan of releasing the source code of version 1.1.1? im trying to extend some feature and contribute it. but i found the source code you published is out of date. and dont have a license, which means i have no permission to contribute. could you open the source of latest release and add a license to it?

你好，想了解一下是否有计划发布1.1.1版本的源码？我想扩展一些功能并为项目做出贡献，但发现推送的源代码已经过时，并没有版权声明。这使得我无法进行贡献。能否请您发布最新版本的源代码，并在其中添加版权声明？

**Comment by Houvven** [comment]
https://github.com/Houvven/Guise/tree/v1

**Comment by Houvven** [comment]
> 似乎“空白通行证”的实现只是通过hook 清除掉查询的结果，实际上仍是需要给予应用权限？

对
