### ISSUE TITLE
大佬，你快点更新吧

### ISSUE THREAD

**Issue by LHC12580** [Houvven/Guise#124]
之前红米k50pro  改机型失效了，王者荣耀又不能120加极致画质了![03883ef4a7c23b46a48f23060c14e823.jpeg](https://github.com/Houvven/Guise/assets/133021043/c56bb259-3fbc-47aa-9867-7841833f7aed)

**Comment by Houvven** [comment]
试下alpha版本

**Comment by LHC12580** [comment]
不是预发行吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月19日(周日) 中午1:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Houvven/Guise] 大佬，你快点更新吧 (Issue #124)




 
试下alpha版本

**Comment by Houvven** [comment]
> 不是预发行吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月19日(周日) 中午1:08 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Houvven/Guise] 大佬，你快点更新吧 (Issue #124) 试下alpha版本 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

是 不过也试下呗

**Comment by LHC12580** [comment]
我刚刚用的是1.1.1，（11）的版本，之前怎么都不行。然后我把王者荣耀&nbsp; 清除数据以后，再打开&nbsp; 然后就成功 王者荣耀&nbsp; 超高帧率+极致画质了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月19日(周日) 中午1:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Houvven/Guise] 大佬，你快点更新吧 (Issue #124)




  
不是预发行吗？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月19日(周日) 中午1:08 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Houvven/Guise] 大佬，你快点更新吧 (Issue #124) 试下alpha版本 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
是 不过也试下呗

**Comment by Houvven** [comment]
王者不用清数据 QQ也不用

**Comment by LHC12580** [comment]
我前面不清楚数据，怎么都改不了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月19日(周日) 中午1:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Houvven/Guise] 大佬，你快点更新吧 (Issue #124)




 
王者不用清数据 QQ也不用
