### ISSUE TITLE
作用域

### ISSUE THREAD

**Issue by xgs33086** [Houvven/Guise#127]
希望增加系统应用作为作用域(比如对系统服务组件伪装语言zh_hans语言可去除游戏加速内的广告)，1.1.2及之前的版本是可以的，2.0.0开始就没办法选择了

**Comment by Houvven** [comment]
首页右滑

**Comment by xgs33086** [comment]
> 首页原来如此，感谢大佬，不过我k50至尊版像这样改k60至尊版改不了😭[Screenshot_2024-05-24-14-33-47-326_com.houvven.guise.jpg](https://github.com/Houvven/Guise/assets/135175047/f9c56275-825e-4d4e-aa66-cd2169ead1c4)

**Comment by Houvven** [comment]
品牌Xiaomi 厂商redmi

**Comment by xgs33086** [comment]
> 品牌Xiaomi 厂商redmi

改了仍旧不行，不知哪里没操作对

**Comment by Houvven** [comment]
已修。[Fix timezone hooker npe](https://github.com/Houvven/Guise/commit/ee420918904c16f491b91ec81aa0c1a2c64bcb3e)

**Comment by Houvven** [comment]
重新下载即可， https://github.com/Houvven/Guise/releases/tag/v2.0.0-Alpha02

**Comment by xgs33086** [comment]
> 重新下载即可， https://github.com/Houvven/Guise/releases/tag/v2.0.0-Alpha02

成功了，谢谢大佬！🌹🌹🌹![Screenshot_2024-05-24-15-58-09-189_com.coolapk.market.jpg](https://github.com/Houvven/Guise/assets/135175047/53bda4b5-8714-41fa-b380-0bb61c01afee)

**Comment by xgs33086** [comment]
> > 重新下载即可， https://github.com/Houvven/Guise/releases/tag/v2.0.0-Alpha02
> 
> 成功了，谢谢大佬！🌹🌹🌹![Screenshot_2024-05-24-15-58-09-189_com.coolapk.market.jpg](https://github.com/Houvven/Guise/assets/135175047/53bda4b5-8714-41fa-b380-0bb61c01afee)
> 
> 

原来只改型号就行？![Screenshot_2024-05-24-15-59-23-159_com.houvven.guise.jpg](https://github.com/Houvven/Guise/assets/135175047/f5dcbf6f-147a-4fc7-a1a3-c80558dbe881)

**Comment by xgs33086** [comment]
> 因为你本来就是Redmi
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 🛶
> ***@***.***
> 
> 
> 
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年5月24日(周五) 下午4:00
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [Houvven/Guise] 作用域 (Issue #127)
> 
> 
> 
> 
>    
> 重新下载即可， https://github.com/Houvven/Guise/releases/tag/v2.0.0-Alpha02
>   
> 成功了，谢谢大佬！🌹🌹🌹Screenshot_2024-05-24-15-58-09-189_com.coolapk.market.jpg (view on web)
>   
> 原来只改型号就行？Screenshot_2024-05-24-15-59-23-159_com.houvven.guise.jpg (view on web)
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

嗯，知道了，我刚刚只填了rog8的型号但是没填品牌，就显示未知错误，所以品牌那里如果不填的话就是默认当前设备的🤣![Screenshot_2024-05-24-16-11-14-382_com.coolapk.market.jpg](https://github.com/Houvven/Guise/assets/135175047/3685a7a2-3ec9-492a-9789-a966e04f41b3)
