### ISSUE TITLE
Can't use it to trick google play store 

### ISSUE THREAD

**Issue by yingshaoxo** [Houvven/Guise#38]
When I download a game called 'sky' in google play store, if my device is Xiaomi, it will not allow me to download.

https://play.google.com/store/apps/details?id=com.tgc.sky.android

![Screenshot_20230528-002314_Google Play Store](https://github.com/Xposed-Modules-Repo/com.houvven.guise/assets/17190829/40ed4e9b-2319-470b-baca-5571f680e507)

My device model is `xiaomi ultra 11 pro`, `M2102K1G`.

![Screenshot_20230528-002720_Settings](https://github.com/Xposed-Modules-Repo/com.houvven.guise/assets/17190829/5f99380f-e0bf-47a9-b7a3-7304ff945c1e)

![Screenshot_20230528-002758_Guise](https://github.com/Xposed-Modules-Repo/com.houvven.guise/assets/17190829/36c801d2-0250-4840-a0ac-e63d88190f6a)

![Screenshot_20230528-002817_LSPosed](https://github.com/Xposed-Modules-Repo/com.houvven.guise/assets/17190829/e69026fb-4535-4623-9eca-62b83b3457e3)

**Comment by Houvven** [comment]
Looks like Google safety
