### ISSUE TITLE
Not activated in LSPosed (in work profile)

### ISSUE THREAD

**Issue by commandblock2** [Houvven/Guise#70]
Not sure if this is a Guise problem, but I will make a issue here anyway, I would be grateful if you can provide any kind of help.
I don't have a android development environment installed on my machine at the moment, I don't know if there is any thing I can do to debug this, Guise logs and LSPosed logs are attached below.
I am willing to provide any extra information if available.
I have another LSPosed module, called Xlogger (in main profile), which can be enabled.

## Environment
AOSP Android 13 GSI, as the dynamic system(DSU).
Magisk 26.1, zygisk enabled, Magisk hide enabled
LSPosed Activated, 1.8.6(6899) - Zygisk
```
API version
100

Xposed API call protection
Enabled

Dex Optimizer Wrapper
Supported

Framework version
1.8.6 (6899)

Manager version
1.8.6 (6899)

System version
13 (API 33)

Device
OnePlus Android PGZ110 

System ABI
arm64-v8a
```

## Logs
LSPosed Log 
[LSPosed_2023-06-16T12_24_54.127529.zip](https://github.com/Houvven/Guise/files/11766067/LSPosed_2023-06-16T12_24_54.127529.zip)

Guise Log
[Guise-log-1686889423416.txt](https://github.com/Houvven/Guise/files/11766073/Guise-log-1686889423416.txt)

## Screenshot
![Screenshot_20230616-122650](https://github.com/Houvven/Guise/assets/21105626/432f9a68-1167-4e26-8dcf-769ca2a7b968)
![Screenshot_20230616-123031](https://github.com/Houvven/Guise/assets/21105626/8f455a88-8d6c-461a-a025-ef795a8365f6)

**Comment by Houvven** [comment]
It has been fixed
